Repository maximezim/PhishAndTips, pull requests merged in 2024-09, with the labels that each got.

#2 Gateway and authentication working together
  authentication/Dockerfile
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationApplication.java
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
  authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
  authentication/src/main/java/com/learnandphish/authentication/JwtRequest.java
  authentication/src/main/java/com/learnandphish/authentication/JwtRequestFilter.java
  authentication/src/main/java/com/learnandphish/authentication/JwtUserDetailsService.java
  authentication/src/main/java/com/learnandphish/authentication/Roles.java
  authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
  authentication/src/main/resources/application.yaml
  docker-compose.yml
  gateway/application.yaml
  gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
  gateway/src/main/java/com/learnandphish/gateway/AuthUtil.java
  gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
  gateway/src/main/java/com/learnandphish/gateway/RouteValidator.java
  gateway/src/main/resources/application.yaml
  gateway/src/test/java/com/learnandphish/gateway/RouteValidatorTest.java
Labels: enhancement

#3 Logging
  .gitignore
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/compiler.xml
  .idea/dataSources.xml
  authentication/Dockerfile
  authentication/build.gradle
  authentication/src/main/resources/application.properties
  authentication/src/main/resources/application.yaml
  docker-compose.yml
  fluent-bit/conf/fluent-bit.conf
  gateway/Dockerfile
  gateway/build.gradle
  gateway/src/main/resources/application.properties
Labels: enhancement

#8 #7 Improved error handling and testing
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
  authentication/src/main/java/com/learnandphish/authentication/JwtUserDetailsService.java
  authentication/src/test/java/com/learnandphish/authentication/JwtUserDetailsServiceTest.java
Labels: enhancement

#13 #12 Validate JWT in the gateway
  authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
  authentication/src/main/java/com/learnandphish/authentication/PublicKeyController.java
  authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
  gateway/build.gradle
  gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
  gateway/src/main/java/com/learnandphish/gateway/AuthUtil.java
  gateway/src/main/java/com/learnandphish/gateway/GatewayApplication.java
  gateway/src/main/java/com/learnandphish/gateway/JWTUtil.java
Labels: bug, enhancement

#15 #14 keep previous key when authentication service restarts
  authentication/Dockerfile
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
  authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
  authentication/src/main/java/com/learnandphish/authentication/PublicKeyController.java
  gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
  gateway/src/main/java/com/learnandphish/gateway/JWTUtil.java
Labels: bug

#17 Swagger UI
  authentication/build.gradle
  authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
  authentication/src/main/resources/application.yaml
  docker-compose.yml
  gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
Labels: bug, enhancement

#19 possibility to change password
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
  authentication/src/main/java/com/learnandphish/authentication/ChangePasswordRequest.java
  authentication/src/main/java/com/learnandphish/authentication/GlobalExceptionHandler.java
  authentication/src/test/java/com/learnandphish/authentication/AuthenticationControllerTest.java
  gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
Labels: enhancement

#20 Added roles to jwt
  authentication/src/main/java/com/learnandphish/authentication/JWTUtil.java
  gateway/build.gradle
  gateway/src/main/java/com/learnandphish/gateway/AuthFilter.java
  gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
  gateway/src/main/java/com/learnandphish/gateway/RouteRoles.java
Labels: enhancement

#21 get user list in csv
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationApplication.java
  authentication/src/main/java/com/learnandphish/authentication/AuthenticationController.java
  authentication/src/main/java/com/learnandphish/authentication/UserData.java
  authentication/src/main/java/com/learnandphish/authentication/UserExportService.java
  authentication/src/main/java/com/learnandphish/authentication/WebSecurityConfig.java
  databases/scripts/authentication_init.sql
  gateway/src/main/java/com/learnandphish/gateway/GatewayConfig.java
Labels: enhancement
